from datetime import datetime

import plotly.graph_objects as go
import streamlit as st

from data import sample_data as d
from services import charts, insights, live_data, llm

SENTIMENT_BADGE = {"Positive": "🟢", "Negative": "🔴", "Neutral": "⚪"}


def _snapshot_line(indices, sectors) -> str:
    top = sorted(sectors, key=lambda s: -s["change"])[:3]
    bottom = sorted(sectors, key=lambda s: s["change"])[:3]
    return (
        "; ".join(f"{i['name']} {i['value']} ({i['change']})" for i in indices)
        + ". Leading sectors: " + ", ".join(f"{s['name']} {s['change']:+.1f}%" for s in top)
        + ". Lagging: " + ", ".join(f"{s['name']} {s['change']:+.1f}%" for s in bottom)
    )


def _source_panel(articles, title="Sources"):
    st.markdown(f"**{title}**")
    st.caption(f"{len(articles)} articles from the approved set")
    for a in articles:
        label = a["title"] if len(a["title"]) <= 80 else a["title"][:78] + "…"
        if a.get("link"):
            st.markdown(f"<small>**{a['source']}** · [{label}]({a['link']})</small>",
                        unsafe_allow_html=True)
        else:
            st.markdown(f"<small>**{a['source']}** · {label}</small>", unsafe_allow_html=True)


def render():
    st.title("Market Dashboard")

    indices, sectors, quotes_live = live_data.get_market_data()
    trend_dates, trend_values, trend_live = live_data.get_sp500_trend()
    headlines, news_live = live_data.get_headlines()

    if quotes_live or news_live:
        status = ("🟢 Live · quotes and news from the approved sources · "
                  f"refreshed {datetime.now():%H:%M}")
    else:
        status = f"⚪ Offline — bundled sample data (as of {d.AS_OF.strftime('%B %d, %Y')})"
    st.caption(f"Barron's · WSJ · CNBC · Seeking Alpha · Yahoo Finance — {status}")

    cols = st.columns(len(indices))
    for col, idx in zip(cols, indices):
        col.metric(idx["name"], idx["value"], idx["change"])

    st.divider()

    # ---------------------------------------------------- AI market outlook
    st.subheader("AI Market Outlook")
    outlook_col, source_col = st.columns([2.4, 1])

    with outlook_col:
        if llm.live():
            try:
                key = insights._key(headlines, "outlook")
                with st.spinner("Synthesising across sources…"):
                    result = insights.market_outlook(key, headlines,
                                                     _snapshot_line(indices, sectors))
                st.markdown(result["summary"])
                st.caption(f"Generated by {llm.provider_label()} from the {len(headlines)} "
                           "articles listed alongside.")
            except Exception as exc:
                st.error(f"Could not generate the outlook: {exc}")
                st.markdown(d.DEMO_OUTLOOK)
        else:
            st.markdown(d.DEMO_OUTLOOK)

    with source_col:
        with st.container(border=True):
            _source_panel(headlines[:10], "Sources used")

    st.divider()

    # ------------------------------------------------------------- charts
    left, right = st.columns(2)

    with left:
        st.subheader("S&P 500 — last 10 sessions")
        if not trend_live:
            st.caption("⚪ sample data")
        fig = go.Figure(go.Scatter(
            x=trend_dates, y=trend_values, mode="lines+markers",
            line=dict(color=charts.SERIES_1, width=2),
            marker=dict(size=6, color=charts.SERIES_1),
            hovertemplate="%{x}<br>%{y:,.0f}<extra></extra>",
        ))
        charts.base_layout(fig)
        st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})

    with right:
        st.subheader("Sector performance — 1 day")
        if not quotes_live:
            st.caption("⚪ sample data")
        s_sorted = sorted(sectors, key=lambda s: s["change"])
        fig = go.Figure(go.Bar(
            x=[s["change"] for s in s_sorted], y=[s["name"] for s in s_sorted],
            orientation="h",
            marker=dict(color=[charts.POS if s["change"] >= 0 else charts.NEG for s in s_sorted],
                        line=dict(width=0)),
            hovertemplate="%{y}: %{x:+.1f}%<extra></extra>",
        ))
        charts.base_layout(fig, height=360)
        fig.update_xaxes(ticksuffix="%")
        fig.update_layout(bargap=0.35)
        st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})

    st.divider()

    # ----------------------------------------------------------- headlines
    head_l, head_r = st.columns([4, 1])
    head_l.subheader("Latest across sources")
    if head_r.button("↻ Refresh", help="Clear the cache and re-pull all feeds"):
        for fn in (live_data.get_headlines, live_data.get_market_data,
                   live_data.get_sp500_trend, live_data.get_sa_analysis):
            fn.clear()
        st.rerun()

    src_filter = st.multiselect(
        "Filter by source",
        options=sorted({h["source"] for h in headlines}),
        placeholder="All sources",
    )
    shown = [h for h in headlines if not src_filter or h["source"] in src_filter]

    for h in shown:
        with st.container(border=True):
            top = st.columns([5, 1])
            title = f"[{h['title']}]({h['link']})" if h.get("link") else f"**{h['title']}**"
            top[0].markdown(title)
            top[1].caption(f"{SENTIMENT_BADGE[h['sentiment']]} {h['sentiment']}")
            st.caption(f"{h['source']} · {h['category']} · {h['time']}")
            if h["summary"]:
                st.write(h["summary"])

    # ------------------------------------------------- AI digest of the news
    if shown and llm.live():
        with st.container(border=True):
            st.markdown("**📋 What this adds up to**")
            try:
                with st.spinner("Summarising the headlines…"):
                    st.markdown(insights.news_digest(insights._key(shown, "digest"), shown))
                st.caption(f"AI summary of the {len(shown)} headlines above · {llm.provider_label()}")
            except Exception as exc:
                st.caption(f"Summary unavailable: {exc}")
    elif shown:
        st.caption("Connect Copilot in the sidebar for an AI summary of these headlines.")
