import streamlit as st

from services import pdf, report_store


def render():
    st.title("Reports Library")
    st.caption("Every report generated in Wisdom Research Hub, kept for reference and reuse.")

    records = report_store.list_reports()

    if not records:
        st.info("No reports yet. Generate one on the **AI Report Generator** page and it will "
                "be filed here automatically.")
        return

    st.caption(
        "⚠️ Stored on the server's disk. This is durable when the app runs locally or on your "
        "own server; on Streamlit Community Cloud the disk resets when the app restarts, so "
        "download anything you need to keep."
    )

    # ------------------------------------------------------------- filters
    f1, f2, f3 = st.columns(3)
    topics = ["All"] + sorted({r["topic"] for r in records})
    topic = f1.selectbox("Topic", topics)
    types = ["All"] + sorted({r["report_type"] for r in records})
    rtype = f2.selectbox("Report type", types)
    langs = ["All"] + sorted({r["language"] for r in records})
    lang = f3.selectbox("Language", langs)

    shown = [
        r for r in records
        if (topic == "All" or r["topic"] == topic)
        and (rtype == "All" or r["report_type"] == rtype)
        and (lang == "All" or r["language"] == lang)
    ]

    st.write(f"**{len(shown)}** of {len(records)} report(s)")

    for r in shown:
        created = r["created"].replace("T", " ")
        with st.expander(f"**{r['topic']}** — {r['report_type']} · {created}"):
            st.caption(
                f"{r['audience']} · {r['length']} · {r['style']} · {r['language']} · "
                f"{r['purpose']}  \nGenerated by {r.get('provider', 'unknown')}"
            )

            full = report_store.get_report(r["id"])
            if not full:
                st.error("This report could not be read back from disk.")
                continue

            st.markdown(full["body"])

            stem = f"{r['topic'][:40].replace(' ', '_')}_{r['id']}"
            spec = (f"{r['report_type']} · {r['audience']} · {r['length']} · "
                    f"{r['style']} · {r['language']} · {r['purpose']}")
            b1, b2, b3 = st.columns([1, 1, 3])
            try:
                b1.download_button(
                    "⬇ .pdf",
                    data=pdf.markdown_to_pdf(full["body"], subtitle=spec),
                    file_name=f"{stem}.pdf",
                    mime="application/pdf",
                    key=f"dlpdf_{r['id']}",
                )
                b2.download_button(
                    "⬇ .docx",
                    data=pdf.markdown_to_docx(full["body"], subtitle=spec),
                    file_name=f"{stem}.docx",
                    mime=("application/vnd.openxmlformats-officedocument"
                          ".wordprocessingml.document"),
                    key=f"dldocx_{r['id']}",
                )
            except Exception as exc:
                b1.download_button(
                    "⬇ .md",
                    data=full["body"],
                    file_name=f"{stem}.md",
                    mime="text/markdown",
                    key=f"dlmd_{r['id']}",
                )
                b2.caption(f"PDF/Word unavailable: {exc}")

            if b3.button("🗑 Delete", key=f"del_{r['id']}"):
                report_store.delete_report(r["id"])
                st.rerun()
