import streamlit as st

from services import report_store


def render():
    st.title("Reports Library")
    st.caption("Every report generated in Wisdom Research Hub, kept for reference and reuse.")

    records = report_store.list_reports()

    if not records:
        st.info("No reports yet. Generate one on the **AI Report Generator** page and it will "
                "be filed here automatically.")
        return

    st.caption(
        "⚠️ Stored on the server's disk. This is durable when the app runs locally or on your "
        "own server; on Streamlit Community Cloud the disk resets when the app restarts, so "
        "download anything you need to keep."
    )

    # ------------------------------------------------------------- filters
    f1, f2, f3 = st.columns(3)
    topics = ["All"] + sorted({r["topic"] for r in records})
    topic = f1.selectbox("Topic", topics)
    types = ["All"] + sorted({r["report_type"] for r in records})
    rtype = f2.selectbox("Report type", types)
    langs = ["All"] + sorted({r["language"] for r in records})
    lang = f3.selectbox("Language", langs)

    shown = [
        r for r in records
        if (topic == "All" or r["topic"] == topic)
        and (rtype == "All" or r["report_type"] == rtype)
        and (lang == "All" or r["language"] == lang)
    ]

    st.write(f"**{len(shown)}** of {len(records)} report(s)")

    for r in shown:
        created = r["created"].replace("T", " ")
        with st.expander(f"**{r['topic']}** — {r['report_type']} · {created}"):
            st.caption(
                f"{r['audience']} · {r['length']} · {r['style']} · {r['language']} · "
                f"{r['purpose']}  \nGenerated by {r.get('provider', 'unknown')}"
            )

            full = report_store.get_report(r["id"])
            if not full:
                st.error("This report could not be read back from disk.")
                continue

            st.markdown(full["body"])

            b1, b2 = st.columns([1, 4])
            b1.download_button(
                "⬇ Download",
                data=full["body"],
                file_name=f"{r['topic'][:40].replace(' ', '_')}_{r['id']}.md",
                mime="text/markdown",
                key=f"dl_{r['id']}",
            )
            if b2.button("🗑 Delete", key=f"del_{r['id']}"):
                report_store.delete_report(r["id"])
                st.rerun()
